Repository codesquad-members-2023/be-java-chess-max, pull requests merged in 2023-06, with the labels that each got.

#1 [Ape] Step 01 완성!
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/chessgame/app/piece/Pawn.java
  src/main/java/com/chessgame/app/piece/PieceColor.java
  src/test/java/com/chessgame/app/piece/PawnTest.java
Labels: step-1

#2 [나그] 구현 계획 작성
  README.md
Labels: documentation

#3 [Fia] step-1 구현
  .gitignore
  main/piece/Color.java
  main/piece/Pawn.java
  test/piece/PawnTest.java
Labels: step-1

#6 [sully] step-1 체스 구현 시작하기
  .gitignore
  build.gradle
  settings.gradle
  src/main/java/Main.java
  src/main/java/pieces/Pawn.java
  src/test/java/pieces/PawnTest.java
Labels: step-1

#8 [브루니] step-1 체스 구현 시작하기
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/chess/color/Color.java
  src/main/java/chess/exception/BusinessException.java
  src/main/java/chess/exception/ErrorCode.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/chess/PawnTest.java
Labels: step-1

#9 [위즈] step-1 체스 구현 시작하기
  .gradle/7.4/checksums/checksums.lock
  .gradle/7.4/dependencies-accessors/dependencies-accessors.lock
  .gradle/7.4/dependencies-accessors/gc.properties
  .gradle/7.4/executionHistory/executionHistory.bin
  .gradle/7.4/executionHistory/executionHistory.lock
  .gradle/7.4/fileChanges/last-build.bin
  .gradle/7.4/fileHashes/fileHashes.bin
  .gradle/7.4/fileHashes/fileHashes.lock
  .gradle/7.4/fileHashes/resourceHashesCache.bin
  .gradle/7.4/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  .gradle/vcs-1/gc.properties
  .idea/.gitignore
  .idea/be-java-chess-max.iml
  .idea/checkstyle-idea.xml
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules/be-java-chess-max.main.iml
  .idea/modules/be-java-chess-max.test.iml
  .idea/vcs.xml
  build.gradle
  build/reports/tests/test/classes/PawnTest.html
  build/reports/tests/test/css/base-style.css
  build/reports/tests/test/css/style.css
  build/reports/tests/test/index.html
  build/reports/tests/test/js/report.js
  build/reports/tests/test/packages/default-package.html
  build/test-results/test/TEST-PawnTest.xml
  build/test-results/test/binary/output.bin
  build/test-results/test/binary/output.bin.idx
  build/test-results/test/binary/results.bin
  build/tmp/compileJava/previous-compilation-data.bin
  build/tmp/compileTestJava/previous-compilation-data.bin
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/Pawn.java
  src/test/java/PawnTest.java
Labels: step-1

#10 [네모네모] step1~4 구현
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/kr/codesqaud/chessgame/ChessApplication.java
  src/main/java/kr/codesqaud/chessgame/chess/Board.java
  src/main/java/kr/codesqaud/chessgame/chess/ChessGame.java
  src/main/java/kr/codesqaud/chessgame/pieces/Color.java
  src/main/java/kr/codesqaud/chessgame/pieces/Piece.java
  src/main/java/kr/codesqaud/chessgame/utils/StringUtils.java
  src/test/java/kr/codesqaud/chess/pieces/PieceTest.java
  src/test/java/kr/codesqaud/chessgame/chess/BoardTest.java
  src/test/java/kr/codesqaud/chessgame/chess/ChessGameTest.java
  src/test/resources/chessBoard.txt
  src/test/resources/commands.txt
Labels: step-4

#4 [Fia] step-2 구현
  main/chess/Board.java
  main/chess/Color.java
  main/chess/piece/Pawn.java
  test/chess/BoardTest.java
  test/chess/piece/PawnTest.java
  test/piece/PawnTest.java
Labels: step-2

#12 [브루니] step-2 체스판 생성
  src/main/java/chess/board/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/chess/board/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: step-2

#14 [나그] Step 1~4 구현
  .gitattributes
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/Application.java
  src/main/java/Board.java
  src/main/java/ChessGame.java
  src/main/java/pieces/Piece.java
  src/main/java/utils/StringUtil.java
  src/test/java/BoardTest.java
  src/test/java/ChessGameTest.java
  src/test/java/PieceTest.java
  src/test/java/StringUtilTest.java
Labels: step-1, step-2, step-3, step-4

#15 [이안] step 1~2 구현
  .gitignore
  build.gradle
  settings.gradle
  src/main/java/chess/Board.java
  src/main/java/pieces/Pawn.java
  src/test/java/chess/BoardTest.java
  src/test/java/pieces/PawnTest.java
Labels: step-1, step-2

#16 [위즈] Step-2 체스판 생성
  .gradle/7.4/executionHistory/executionHistory.bin
  .gradle/7.4/executionHistory/executionHistory.lock
  .gradle/7.4/fileHashes/fileHashes.bin
  .gradle/7.4/fileHashes/fileHashes.lock
  .gradle/7.4/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  .idea/gradle.xml
  .idea/misc.xml
  .idea/modules/be-java-chess-max.main.iml
  .idea/modules/be-java-chess-max.test.iml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  build/reports/tests/test/classes/chess.BoardTest.html
  build/reports/tests/test/index.html
  build/reports/tests/test/packages/chess.html
  build/test-results/test/TEST-PawnTest.xml
  build/test-results/test/TEST-chess.BoardTest.xml
  build/test-results/test/binary/results.bin
  build/tmp/compileJava/previous-compilation-data.bin
  build/tmp/compileTestJava/previous-compilation-data.bin
  src/main/java/Pawn.java
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/PawnTest.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: step-2

#17 [Ape] 3단계 구현
  src/main/java/com/chessgame/app/chess/Main.java
  src/main/java/com/chessgame/app/chess/board/Board.java
  src/main/java/com/chessgame/app/chess/piece/Pawn.java
  src/main/java/com/chessgame/app/chess/piece/Piece.java
  src/main/java/com/chessgame/app/chess/piece/position/File.java
  src/main/java/com/chessgame/app/chess/piece/position/Position.java
  src/main/java/com/chessgame/app/chess/piece/position/Rank.java
  src/main/java/com/chessgame/app/chess/piece/type/PieceColor.java
  src/main/java/com/chessgame/app/chess/piece/type/PieceSymbol.java
  src/main/java/com/chessgame/app/chess/piece/type/PieceType.java
  src/main/java/com/chessgame/app/chess/piece/utill/PieceInitializer.java
  src/main/java/com/chessgame/app/chess/piece/utill/PieceSymbolGenerator.java
  src/main/java/com/chessgame/app/piece/Pawn.java
  src/main/java/com/chessgame/app/piece/PieceColor.java
  src/test/java/com/chessgame/app/chess/board/BoardTest.java
  src/test/java/com/chessgame/app/chess/piece/PawnTest.java
  src/test/java/com/chessgame/app/piece/PawnTest.java
Labels: step-3

#18 [브루니] step-3 보드 초기화하기
  src/main/java/chess/ChessApplication.java
  src/main/java/chess/board/Board.java
  src/main/java/chess/game/ChessGame.java
  src/main/java/chess/pieces/Dummy.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/view/InputUtils.java
  src/test/java/chess/board/BoardTest.java
Labels: step-3

#19 [이안] step-3~4 구현
  src/main/java/chess/Board.java
  src/main/java/chess/ChessGame.java
  src/main/java/pieces/Pawn.java
  src/main/java/pieces/Piece.java
  src/main/java/utils/StringUtils.java
  src/test/java/chess/BoardTest.java
  src/test/java/pieces/PawnTest.java
  src/test/java/pieces/PieceTest.java
  src/test/java/utils/StringUtilsTest.java
Labels: step-3, step-4

#21 [Fia] step-4 구현
  main/chess/Board.java
  main/chess/ChessGame.java
  main/chess/Name.java
  main/chess/StringUtil.java
  main/chess/piece/Pawn.java
  main/chess/piece/Piece.java
  test/chess/BoardTest.java
  test/chess/piece/PawnTest.java
  test/chess/piece/PieceTest.java
Labels: step-4

#22 [파이] - Step1, 2 체스 구현 시작 / 체스판 생성
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/chess/board/Board.java
  src/main/java/chess/color/Color.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/chess/board/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: step-1, step-2

#23 [위즈] Step-3 체스판 초기화
  .gradle/7.4/executionHistory/executionHistory.bin
  .gradle/7.4/executionHistory/executionHistory.lock
  .gradle/7.4/fileHashes/fileHashes.bin
  .gradle/7.4/fileHashes/fileHashes.lock
  .gradle/7.4/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  build/reports/tests/test/classes/chess.BoardTest.html
  build/reports/tests/test/index.html
  build/reports/tests/test/packages/chess.html
  build/test-results/test/TEST-chess.BoardTest.xml
  build/test-results/test/binary/output.bin
  build/test-results/test/binary/output.bin.idx
  build/test-results/test/binary/results.bin
  build/tmp/compileJava/previous-compilation-data.bin
  build/tmp/compileTestJava/previous-compilation-data.bin
  src/main/java/chess/Board.java
  src/main/java/chess/ChessGame.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: step-3

#24 [sully] step-4 모든 기물 배치하기
  src/main/java/Main.java
  src/main/java/chess/Board.java
  src/main/java/chess/Game.java
  src/main/java/pieces/Pawn.java
  src/main/java/pieces/Piece.java
  src/main/java/pieces/PieceColor.java
  src/main/java/utils/StringUtils.java
  src/test/java/chess/BoardTest.java
  src/test/java/pieces/PawnTest.java
  src/test/java/pieces/PieceTest.java
Labels: step-4

#25 [Fia] step-5 구현
  main/chess/Board.java
  main/chess/Color.java
  main/chess/Name.java
  main/chess/Rank.java
  main/chess/piece/Piece.java
  main/chess/piece/Position.java
  main/chess/util/StringUtil.java
  test/chess/BoardTest.java
  test/chess/piece/PieceTest.java
Labels: step-5

#27 [브루니] step-4 모든 기물 배치하기
  build.gradle
  src/main/java/chess/board/Board.java
  src/main/java/chess/pieces/Bishop.java
  src/main/java/chess/pieces/Dummy.java
  src/main/java/chess/pieces/King.java
  src/main/java/chess/pieces/Knight.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/Queen.java
  src/main/java/chess/pieces/Rook.java
  src/main/java/chess/pieces/type/Type.java
  src/test/java/chess/board/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: step-4

#28 [나그]: step-5 구현
  README.md
  src/main/java/Application.java
  src/main/java/Board.java
  src/main/java/controller/ChessGame.java
  src/main/java/pieces/Board.java
  src/main/java/pieces/Piece.java
  src/main/java/pieces/Rank.java
  src/test/java/BoardTest.java
  src/test/java/PieceTest.java
  src/test/java/controllerTest/ChessGameTest.java
  src/test/java/piecesTest/BoardTest.java
  src/test/java/piecesTest/PieceTest.java
  src/test/java/piecesTest/RankTest.java
  src/test/java/utilTest/StringUtilTest.java
Labels: step-5

#29 [Albert] Step1~Step4
  .gitignore
  .idea/.gitignore
  .idea/misc.xml
  .idea/vcs.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Color.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/PieceCreator.java
  src/main/java/chess/pieces/Representation.java
  src/main/java/chess/pieces/Type.java
  src/main/java/chess/pieces/bishop/Bishop.java
  src/main/java/chess/pieces/bishop/BlackBishop.java
  src/main/java/chess/pieces/bishop/WhiteBishop.java
  src/main/java/chess/pieces/king/BlackKing.java
  src/main/java/chess/pieces/king/King.java
  src/main/java/chess/pieces/king/WhiteKing.java
  src/main/java/chess/pieces/knight/BlackKnight.java
  src/main/java/chess/pieces/knight/Knight.java
  src/main/java/chess/pieces/knight/WhiteKnight.java
  src/main/java/chess/pieces/pawn/BlackPawn.java
  src/main/java/chess/pieces/pawn/Pawn.java
  src/main/java/chess/pieces/pawn/WhitePawn.java
  src/main/java/chess/pieces/queen/BlackQueen.java
  src/main/java/chess/pieces/queen/Queen.java
  src/main/java/chess/pieces/queen/WhiteQueen.java
  src/main/java/chess/pieces/rook/BlackRook.java
  src/main/java/chess/pieces/rook/Rook.java
  src/main/java/chess/pieces/rook/WhiteRook.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PieceCreatorTest.java
  src/test/java/chess/pieces/bishop/BishopTest.java
  src/test/java/chess/pieces/bishop/BlackBishopTest.java
  src/test/java/chess/pieces/bishop/WhiteBishopTest.java
  src/test/java/chess/pieces/king/BlackKingTest.java
  src/test/java/chess/pieces/king/KingTest.java
  src/test/java/chess/pieces/king/WhiteKingTest.java
  src/test/java/chess/pieces/knight/BlackKnightTest.java
  src/test/java/chess/pieces/knight/KnightTest.java
  src/test/java/chess/pieces/knight/WhiteKnightTest.java
  src/test/java/chess/pieces/pawn/BlackPawnTest.java
  src/test/java/chess/pieces/pawn/PawnTest.java
  src/test/java/chess/pieces/pawn/WhitePawnTest.java
  src/test/java/chess/pieces/queen/BlackQueenTest.java
  src/test/java/chess/pieces/queen/QueenTest.java
  src/test/java/chess/pieces/queen/WhiteQueenTest.java
  src/test/java/chess/pieces/rook/BlackRookTest.java
  src/test/java/chess/pieces/rook/RookTest.java
  src/test/java/chess/pieces/rook/WhiteRookTest.java
Labels: step-1, step-2, step-3, step-4

#31 [위즈] Step-4 모든 기물 배치하기
  src/main/java/chess/Board.java
  src/main/java/chess/ChessGame.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/utils/StringUtils.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/chess/pieces/PieceTest.java
Labels: step-4

#32 [이안] step-5 구현
  src/main/java/chess/Board.java
  src/main/java/chess/Rank.java
  src/main/java/pieces/Bishop.java
  src/main/java/pieces/Blank.java
  src/main/java/pieces/King.java
  src/main/java/pieces/Knight.java
  src/main/java/pieces/Pawn.java
  src/main/java/pieces/Piece.java
  src/main/java/pieces/Position.java
  src/main/java/pieces/Queen.java
  src/main/java/pieces/Rook.java
  src/test/java/chess/BoardTest.java
  src/test/java/pieces/PieceTest.java
Labels: step-5

#33 [브루니] step-5 보드에 위치 부여 및 점수 계산
  src/main/java/chess/board/Board.java
  src/main/java/chess/board/Position.java
  src/main/java/chess/board/Rank.java
  src/main/java/chess/exception/ErrorCode.java
  src/main/java/chess/pieces/Bishop.java
  src/main/java/chess/pieces/King.java
  src/main/java/chess/pieces/Knight.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/Queen.java
  src/main/java/chess/pieces/Rook.java
  src/main/java/chess/pieces/color/Color.java
  src/main/java/chess/pieces/type/Type.java
  src/test/java/chess/board/BoardTest.java
  src/test/java/chess/board/PositionTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: step-5

#34 [Ape] Step 05 구현
  src/main/java/com/chessgame/app/chess/board/Board.java
  src/main/java/com/chessgame/app/chess/piece/Piece.java
  src/main/java/com/chessgame/app/chess/piece/position/File.java
  src/main/java/com/chessgame/app/chess/piece/position/Position.java
  src/main/java/com/chessgame/app/chess/piece/position/Rank.java
  src/main/java/com/chessgame/app/chess/piece/type/PieceColor.java
  src/main/java/com/chessgame/app/chess/piece/type/PieceKind.java
  src/main/java/com/chessgame/app/chess/piece/type/PieceType.java
  src/main/java/com/chessgame/app/chess/piece/utill/PieceInitializer.java
  src/main/java/com/chessgame/app/chess/piece/utill/PieceSymbolGenerator.java
  src/main/java/com/chessgame/app/chess/piece/utill/PieceTypeGenerator.java
  src/main/java/com/chessgame/app/chess/piece/utill/PositionGenerator.java
  src/test/java/com/chessgame/app/chess/board/BoardTest.java
  src/test/java/com/chessgame/app/chess/piece/PawnTest.java
Labels: step-5

#35 [위즈] Step-5 보드에 위치 부여 및 점수 계산
  src/main/java/chess/Board.java
  src/main/java/chess/Rank.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/Position.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PieceTest.java
Labels: step-5

#36 [Albert] Step5,6,7 기능구현
  src/main/java/chess/Board.java
  src/main/java/chess/BoardUtility.java
  src/main/java/chess/Chess.java
  src/main/java/chess/ChessView.java
  src/main/java/chess/Game.java
  src/main/java/chess/InputView.java
  src/main/java/chess/Position.java
  src/main/java/chess/pieces/BlankPiece.java
  src/main/java/chess/pieces/Color.java
  src/main/java/chess/pieces/DefaultPiece.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/PieceCreator.java
  src/main/java/chess/pieces/PieceUtility.java
  src/main/java/chess/pieces/Representation.java
  src/main/java/chess/pieces/Type.java
  src/main/java/chess/pieces/bishop/Bishop.java
  src/main/java/chess/pieces/bishop/BlackBishop.java
  src/main/java/chess/pieces/bishop/WhiteBishop.java
  src/main/java/chess/pieces/king/BlackKing.java
  src/main/java/chess/pieces/king/King.java
  src/main/java/chess/pieces/king/WhiteKing.java
  src/main/java/chess/pieces/knight/BlackKnight.java
  src/main/java/chess/pieces/knight/Knight.java
  src/main/java/chess/pieces/knight/WhiteKnight.java
  src/main/java/chess/pieces/pawn/BlackPawn.java
  src/main/java/chess/pieces/pawn/Pawn.java
  src/main/java/chess/pieces/pawn/WhitePawn.java
  src/main/java/chess/pieces/queen/BlackQueen.java
  src/main/java/chess/pieces/queen/Queen.java
  src/main/java/chess/pieces/queen/WhiteQueen.java
  src/main/java/chess/pieces/rook/BlackRook.java
  src/main/java/chess/pieces/rook/Rook.java
  src/main/java/chess/pieces/rook/WhiteRook.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PieceCreatorTest.java
  src/test/java/chess/pieces/bishop/BishopTest.java
  src/test/java/chess/pieces/bishop/BlackBishopTest.java
  src/test/java/chess/pieces/bishop/WhiteBishopTest.java
  src/test/java/chess/pieces/king/BlackKingTest.java
  src/test/java/chess/pieces/king/KingTest.java
  src/test/java/chess/pieces/king/WhiteKingTest.java
  src/test/java/chess/pieces/knight/BlackKnightTest.java
  src/test/java/chess/pieces/knight/KnightTest.java
  src/test/java/chess/pieces/knight/WhiteKnightTest.java
  src/test/java/chess/pieces/pawn/BlackPawnTest.java
  src/test/java/chess/pieces/pawn/WhitePawnTest.java
  src/test/java/chess/pieces/queen/BlackQueenTest.java
  src/test/java/chess/pieces/queen/QueenTest.java
  src/test/java/chess/pieces/queen/WhiteQueenTest.java
  src/test/java/chess/pieces/rook/BlackRookTest.java
  src/test/java/chess/pieces/rook/RookTest.java
  src/test/java/chess/pieces/rook/WhiteRookTest.java
Labels: step-5, step-6, step-7

#37 [네모네모] step5-구현
  src/main/java/kr/codesqaud/chessgame/ChessApplication.java
  src/main/java/kr/codesqaud/chessgame/chess/Board.java
  src/main/java/kr/codesqaud/chessgame/chess/ChessBoard.java
  src/main/java/kr/codesqaud/chessgame/chess/ChessGame.java
  src/main/java/kr/codesqaud/chessgame/chess/Rank.java
  src/main/java/kr/codesqaud/chessgame/pieces/Color.java
  src/main/java/kr/codesqaud/chessgame/pieces/Piece.java
  src/main/java/kr/codesqaud/chessgame/pieces/PieceFactory.java
  src/main/java/kr/codesqaud/chessgame/pieces/Position.java
  src/main/java/kr/codesqaud/chessgame/pieces/Type.java
  src/main/java/kr/codesqaud/chessgame/utils/StringUtils.java
  src/test/java/kr/codesqaud/chess/pieces/PieceTest.java
  src/test/java/kr/codesqaud/chessgame/chess/BoardTest.java
  src/test/java/kr/codesqaud/chessgame/chess/ChessBoardTest.java
  src/test/java/kr/codesqaud/chessgame/chess/ChessGameTest.java
  src/test/java/kr/codesqaud/chessgame/pieces/PositionTest.java
Labels: step-5

#38 [Fia] step-6 구현
  main/chess/Board.java
  main/chess/ChessGame.java
  main/chess/ChessGameStarter.java
  main/chess/Rank.java
  main/chess/exception/EmptyPieceMoveException.java
  main/chess/exception/InvalidPositionException.java
  main/chess/exception/InvalidTurnException.java
  main/chess/piece/Bishop.java
  main/chess/piece/Blank.java
  main/chess/piece/Color.java
  main/chess/piece/Direction.java
  main/chess/piece/King.java
  main/chess/piece/Knight.java
  main/chess/piece/Pawn.java
  main/chess/piece/Piece.java
  main/chess/piece/Position.java
  main/chess/piece/Queen.java
  main/chess/piece/Rook.java
  main/chess/piece/Type.java
  main/chess/util/StringUtil.java
  main/chess/view/ChessView.java
  test/chess/BoardTest.java
  test/chess/ChessGameTest.java
  test/chess/piece/BishopTest.java
  test/chess/piece/KingTest.java
  test/chess/piece/KnightTest.java
  test/chess/piece/PawnTest.java
  test/chess/piece/PieceTest.java
  test/chess/piece/QueenTest.java
  test/chess/piece/RookTest.java
Labels: step-6

#39 [파이] Step-3 체스판 초기화
  README.md
  src/main/java/ChessGame.java
  src/main/java/chess/board/Board.java
  src/main/java/chess/pieces/Blank.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/test/java/chess/board/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: step-3

#40 [브루니] step-6 기물 이동 구현
  src/main/java/chess/board/Board.java
  src/main/java/chess/board/Position.java
  src/main/java/chess/board/Rank.java
  src/main/java/chess/game/ChessGame.java
  src/main/java/chess/pieces/Bishop.java
  src/main/java/chess/pieces/King.java
  src/main/java/chess/pieces/Knight.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/Queen.java
  src/main/java/chess/pieces/Rook.java
  src/main/java/chess/pieces/direction/Direction.java
  src/main/java/chess/view/ChessView.java
  src/test/java/chess/board/BoardTest.java
  src/test/java/chess/pieces/BishopTest.java
  src/test/java/chess/pieces/KingTest.java
  src/test/java/chess/pieces/KnightTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/chess/pieces/QueenTest.java
  src/test/java/chess/pieces/RookTest.java
  src/test/java/chess/view/ChessViewTest.java
Labels: step-6

#41 [브루니] step-6 기물 이동 구현
  src/main/java/chess/board/Board.java
  src/main/java/chess/exception/ErrorCode.java
  src/main/java/chess/game/ChessGame.java
  src/main/java/chess/pieces/Bishop.java
  src/main/java/chess/pieces/King.java
  src/main/java/chess/pieces/Knight.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/Queen.java
  src/main/java/chess/pieces/Rook.java
  src/main/java/chess/pieces/color/Color.java
  src/main/java/chess/pieces/direction/Direction.java
  src/main/java/chess/view/InputUtils.java
  src/test/java/chess/board/BoardTest.java
  src/test/java/chess/pieces/BishopTest.java
  src/test/java/chess/pieces/KingTest.java
  src/test/java/chess/pieces/KnightTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/chess/pieces/QueenTest.java
  src/test/java/chess/pieces/RookTest.java
Labels: step-6

#43 [브루니] step-8 웹으로 구현 (일부)
  src/main/java/chess/game/ChessGame.java
  src/main/java/web/ChessGameWebApplication.java
  src/main/java/web/application/ChessService.java
  src/main/java/web/exception/ErrorResponse.java
  src/main/java/web/exception/GlobalExceptionHandler.java
  src/main/java/web/presentation/ChessController.java
  src/main/java/web/presentation/dto/MoveRequest.java
  src/main/java/web/presentation/dto/MoveResponse.java
Labels: step-7, step-8

#44 [파이] Step4 모든 기물 배치하기
  README.md
  src/main/java/chess/board/Board.java
  src/main/java/chess/pieces/Bishop.java
  src/main/java/chess/pieces/Blank.java
  src/main/java/chess/pieces/King.java
  src/main/java/chess/pieces/Knight.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/Queen.java
  src/main/java/chess/pieces/Rook.java
  src/test/java/chess/board/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: step-4

#45 [네모네모] step8 - 구현
  build.gradle
  src/main/java/kr/codesqaud/chessgame/ChessGameConsoleApplication.java
  src/main/java/kr/codesqaud/chessgame/ChessGameWebApplication.java
  src/main/java/kr/codesqaud/chessgame/chess/ChessGame.java
  src/main/java/kr/codesqaud/chessgame/chess/board/Board.java
  src/main/java/kr/codesqaud/chessgame/chess/board/ChessBoard.java
  src/main/java/kr/codesqaud/chessgame/chess/board/Rank.java
  src/main/java/kr/codesqaud/chessgame/chess/pieces/Bishop.java
  src/main/java/kr/codesqaud/chessgame/chess/pieces/Blank.java
  src/main/java/kr/codesqaud/chessgame/chess/pieces/King.java
  src/main/java/kr/codesqaud/chessgame/chess/pieces/Knight.java
  src/main/java/kr/codesqaud/chessgame/chess/pieces/Pawn.java
  src/main/java/kr/codesqaud/chessgame/chess/pieces/Piece.java
  src/main/java/kr/codesqaud/chessgame/chess/pieces/Position.java
  src/main/java/kr/codesqaud/chessgame/chess/pieces/Queen.java
  src/main/java/kr/codesqaud/chessgame/chess/pieces/Rook.java
  src/main/java/kr/codesqaud/chessgame/chess/pieces/config/Color.java
  src/main/java/kr/codesqaud/chessgame/controller/ConsoleChessGameController.java
  src/main/java/kr/codesqaud/chessgame/web/ApiChessController.java
  src/main/java/kr/codesqaud/chessgame/web/ChessController.java
  src/main/java/kr/codesqaud/chessgame/web/ChessDto.java
  src/main/java/kr/codesqaud/chessgame/web/MvcConfiguration.java
  src/main/java/kr/codesqaud/chessgame/web/Result.java
  src/main/resources/application.properties
  src/main/resources/static/js/chessboard.js
  src/main/resources/templates/chessboard.html
  src/test/java/kr/codesqaud/chessgame/chess/ChessBoardTest.java
  src/test/java/kr/codesqaud/chessgame/pieces/PositionTest.java
  src/test/resources/chessBoard.txt
Labels: step-8
